### ISSUE TITLE
WebApiAssemblyToSwaggerGenerator support for multiple assemblies?

### ISSUE THREAD

**Issue by davidkeaveny** [NSwag/NSwag#175]
Are there any plans to add support for generating a Swagger spec from multiple assemblies containing WebAPI controllers? If not, how best to merge together more than one Swagger spec?

**Comment by rsuter** [comment]
How are you using NSwag? In the UI?

**Comment by davidkeaveny** [comment]
My preference would be to use it in the build process, so that when I compile my assemblies with API controllers, the Swagger definition would be automatically updated. This updated definition could then be picked up by later steps in the build process, and used to e.g. generate C#/TypeScript clients, or generate a changelist based on diffs of the definition.

**Comment by rsuter** [comment]
Ok, then you probably should use the msbuild targets nuget package with the bundled cmd line tools. I have to check how to enhance the tools to support muliple assemblies (without breaking the current interface).

**Comment by rsuter** [comment]
For now, your best option is to use the owin middleware and serve the swagger spec via url route. I think the middleware supports multiple assemblies.. is this an option?

**Comment by rsuter** [comment]
Added multi assembly support: https://github.com/NSwag/NSwag/commit/fb6384739d98a0f629672ea3e19000a04dd3b59b

After release, you can use the msbuild targets: https://github.com/NSwag/NSwag/wiki/MSBuild

**Comment by rsuter** [comment]
Also see command line docu: https://github.com/NSwag/NSwag/wiki/CommandLine

**Comment by davidkeaveny** [comment]
I'll give that a go this afternoon and let you know how it turns out.

**Comment by rsuter** [comment]
Yew, please download the latest ci artifacts and try with that. If everything is fine, ill create a new release...

**Comment by rsuter** [comment]
Release v3.11

**Comment by davidkeaveny** [comment]
Sorry for the delay in getting back to you, constantly changing work priorities keep getting in the way. I've installed NSwag.MSBuild.3.14.0 from NuGet, and set up my AfterBuild event as per the wiki, specifying all my assemblies to parse, but I get the following error:

```
NSwag command line: v3.14.6023.40066
Visit http://NSwag.org for more information.
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Sequence contains more than one matching element

Server stack trace:
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at NSwag.CodeGeneration.SwaggerGenerators.WebApi.WebApiToSwaggerGenerator.GetHttpPath(SwaggerService service, SwaggerOperation operation, Type controllerType, MethodInfo method, List`1 parameters, ISchemaResolver schemaResolver)
   at NSwag.CodeGeneration.SwaggerGenerators.WebApi.WebApiToSwaggerGenerator.GenerateForController(SwaggerService service, Type controllerType, String excludedMethodName, SchemaResolver schemaResolver)
   at NSwag.CodeGeneration.SwaggerGenerators.WebApi.WebApiToSwaggerGenerator.GenerateForControllers(IEnumerable`1 controllerTypes, String excludedMethodName)
   at NSwag.CodeGeneration.SwaggerGenerators.WebApi.WebApiAssemblyToSwaggerGenerator.WebApiAssemblyLoader.GenerateForControllers(IEnumerable`1 controllerClassNames, String settingsData)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NSwag.CodeGeneration.SwaggerGenerators.WebApi.WebApiAssemblyToSwaggerGenerator.WebApiAssemblyLoader.GenerateForControllers(IEnumerable`1 controllerClassNames, String settingsData)
   at NSwag.CodeGeneration.SwaggerGenerators.WebApi.WebApiAssemblyToSwaggerGenerator.GenerateForControllers(IEnumerable`1 controllerClassNames)
   at NSwag.Commands.WebApiToSwaggerCommand.<RunAsync>b__41_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.WebApiToSwaggerCommand.<RunAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.WebApiToSwaggerCommand.<RunAsync>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NConsole.CommandLineProcessor.<ProcessSingleAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NConsole.CommandLineProcessor.<ProcessAsync>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at NSwag.Program.Main(String[] args)
---> (Inner Exception #0) System.InvalidOperationException: Sequence contains more than one matching element

Server stack trace:
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at NSwag.CodeGeneration.SwaggerGenerators.WebApi.WebApiToSwaggerGenerator.GetHttpPath(SwaggerService service, SwaggerOperation operation, Type controllerType, MethodInfo method, List`1 parameters, ISchemaResolver schemaResolver)
   at NSwag.CodeGeneration.SwaggerGenerators.WebApi.WebApiToSwaggerGenerator.GenerateForController(SwaggerService service, Type controllerType, String excludedMethodName, SchemaResolver schemaResolver)
   at NSwag.CodeGeneration.SwaggerGenerators.WebApi.WebApiToSwaggerGenerator.GenerateForControllers(IEnumerable`1 controllerTypes, String excludedMethodName)
   at NSwag.CodeGeneration.SwaggerGenerators.WebApi.WebApiAssemblyToSwaggerGenerator.WebApiAssemblyLoader.GenerateForControllers(IEnumerable`1 controllerClassNames, String settingsData)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NSwag.CodeGeneration.SwaggerGenerators.WebApi.WebApiAssemblyToSwaggerGenerator.WebApiAssemblyLoader.GenerateForControllers(IEnumerable`1 controllerClassNames, String settingsData)
   at NSwag.CodeGeneration.SwaggerGenerators.WebApi.WebApiAssemblyToSwaggerGenerator.GenerateForControllers(IEnumerable`1 controllerClassNames)
   at NSwag.Commands.WebApiToSwaggerCommand.<RunAsync>b__41_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.WebApiToSwaggerCommand.<RunAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.WebApiToSwaggerCommand.<RunAsync>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NConsole.CommandLineProcessor.<ProcessSingleAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NConsole.CommandLineProcessor.<ProcessAsync>d__8.MoveNext()<---
```

I get the same error if I run directly from the command line. I've narrowed it down to one of my assemblies, the other assemblies seem to have no issue, either individually or combined. I'm wondering whether the error means that I have two controller actions that generate the same URI or unique name based on the default naming conventions, but that's just a guess.

**Comment by rsuter** [comment]
The problem is that you have an action with multiple RouteAttributes which is currently not supported. For now just create one method per route... see https://github.com/NSwag/NSwag/issues/63

**Comment by davidkeaveny** [comment]
Fair enough; it would be helpful if the error message identified the controller action being processed at the time though.

**Comment by rsuter** [comment]
Or I make a simple fix and just ignore the other routes (ie use FirstOrDefault instead of SingleOrDefault). Should i implement this fix?

**Comment by davidkeaveny** [comment]
Anyway, I can confirm that multiple assembly support works fine. Awesome response, thanks! I'll watch for the outcome of #63 .

**Comment by davidkeaveny** [comment]
Maybe just go with the simple fix for now, as far as this ticket is concerned? Once #63 is resolved, that should be enough anyway, and in the meantime, I can just code around the multiple routes on an action.

**Comment by rsuter** [comment]
Now just processes first RouteAttribute, the others are ignored: https://github.com/NSwag/NSwag/commit/b1afed7317606676c96f3740aa6a582c9d5577d3

**Comment by rsuter** [comment]
Try v3.15

**Comment by davidkeaveny** [comment]
That works, for sure. 

It does mean that I have an action out there somewhere that has one or more routes not being documented, but I can probably live with that until support for multiple routes is implemented. 

For reference, NSwag takes about 4 minutes to generate the Swagger definition from my API, which has about 100 controllers with something like 600 actions in total (Thinkpad T550, i7 quad core, 16GB RAM, SSD).
