### ISSUE TITLE
Question about OutputFilePath

### ISSUE THREAD

**Issue by ismcagdas** [NSwag/NSwag#413]
Hi,

I was trying to run npm package.
I have used *.nswag file to generate angular2 typescript proxies.

When I have an OutputFilePath like this
`"OutputFilePath": "..\\src\\shared\\service-proxies\\service-proxies.ts"`
I got an error but if I use full path like "D:\\.................\\service-proxies.ts" it works.

Can we use relative paths for OutputFilePath ? If so, can you share an example ?

Here is the exception message I'm getting.

System.AggregateException: One or more errors occurred. ---> System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at NSwag.CodeGeneration.Utilities.PathUtilities.MakeAbsolutePath(String relativePath, String relativeTo) in C:\Data\NSwag\src\NSwag.AssemblyLoaderCore\Utilities\PathUtilities.cs:line 83
   at NSwag.Commands.NSwagDocumentBase.ConvertToAbsolutePaths() in C:\Data\NSwag\src\NSwag.Commands\NSwagDocumentBase.cs:line 250
   at NSwag.Commands.NSwagDocumentBase.<>c__DisplayClass59_0`1.<LoadAsync>b__0() in C:\Data\NSwag\src\NSwag.Commands\NSwagDocumentBase.cs:line 159
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.CodeGeneration.Commands.NSwagDocumentCommand.<LoadDocumentAsync>d__0.MoveNext() in C:\Data\NSwag\src\NSwag.AssemblyLoaderCore\Commands\NSwagDocumentCommand.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.NSwagDocumentCommandBase.<ExecuteDocumentAsync>d__5.MoveNext() in C:\Data\NSwag\src\NSwag.Commands\Commands\NSwagDocumentCommandBase.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.NSwagDocumentCommandBase.<RunAsync>d__4.MoveNext() in C:\Data\NSwag\src\NSwag.Commands\Commands\NSwagDocumentCommandBase.cs:line 28
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NConsole.CommandLineProcessor.<ProcessSingleAsync>d__12.MoveNext() in C:\projects\nconsole\src\NConsole\CommandLineProcessor.cs:line 138
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NConsole.CommandLineProcessor.<ProcessAsync>d__11.MoveNext() in C:\projects\nconsole\src\NConsole\CommandLineProcessor.cs:line 107
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\Data\NSwag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 39
---> (Inner Exception #0) System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at NSwag.CodeGeneration.Utilities.PathUtilities.MakeAbsolutePath(String relativePath, String relativeTo) in C:\Data\NSwag\src\NSwag.AssemblyLoaderCore\Utilities\PathUtilities.cs:line 83
   at NSwag.Commands.NSwagDocumentBase.ConvertToAbsolutePaths() in C:\Data\NSwag\src\NSwag.Commands\NSwagDocumentBase.cs:line 250
   at NSwag.Commands.NSwagDocumentBase.<>c__DisplayClass59_0`1.<LoadAsync>b__0() in C:\Data\NSwag\src\NSwag.Commands\NSwagDocumentBase.cs:line 159
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.CodeGeneration.Commands.NSwagDocumentCommand.<LoadDocumentAsync>d__0.MoveNext() in C:\Data\NSwag\src\NSwag.AssemblyLoaderCore\Commands\NSwagDocumentCommand.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.NSwagDocumentCommandBase.<ExecuteDocumentAsync>d__5.MoveNext() in C:\Data\NSwag\src\NSwag.Commands\Commands\NSwagDocumentCommandBase.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.NSwagDocumentCommandBase.<RunAsync>d__4.MoveNext() in C:\Data\NSwag\src\NSwag.Commands\Commands\NSwagDocumentCommandBase.cs:line 28
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NConsole.CommandLineProcessor.<ProcessSingleAsync>d__12.MoveNext() in C:\projects\nconsole\src\NConsole\CommandLineProcessor.cs:line 138
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NConsole.CommandLineProcessor.<ProcessAsync>d__11.MoveNext() in C:\projects\nconsole\src\NConsole\CommandLineProcessor.cs:line 107<---

Thanks a lot.

**Comment by rsuter** [comment]
Relative paths are allowed, but must be relative to the nswag file. Is this the case?

**Comment by ismcagdas** [comment]
Hi,

Thank you for your response. Yes, it's relative to nswag file.
I'm attaching some screenshots to make it more clear.

This is the error message:
![image](https://cloud.githubusercontent.com/assets/4133525/20178550/651564c8-a75a-11e6-8de4-ad101828b912.png)

These are the locations of nswag file and output file directories.

![image](https://cloud.githubusercontent.com/assets/4133525/20178596/a216b584-a75a-11e6-9729-d1d11d55c30f.png)

and I'm using an outputfilepath like this.
`"OutputFilePath": "..\\src\\shared\\service-proxies\\service-proxies.ts"`

**Comment by rsuter** [comment]
Can you try `nswag run` without file name?

**Comment by ismcagdas** [comment]
Thanks, It works that way 😊

**Comment by rsuter** [comment]
Ok, then you found a bug which i can reproduce.. will be fixed in the next version...

**Comment by ismcagdas** [comment]
Thanks for your great work. 
We can continue with your solution at the moment.

**Comment by rsuter** [comment]
Will be fixed in v7.1
