### ISSUE TITLE
Generating from a parameter that implements IEnumerable<T> throws exception

### ISSUE THREAD

**Issue by georgeonofrei** [NSwag/NSwag#419]
**Exception details**:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at NSwag.CodeGeneration.SwaggerGenerators.SwaggerGenerator.GenerateAndAppendSchemaFromType(Type type, Boolean mayBeNull, IEnumerable`1 parentAttributes) in C:\projects\nswag\src\NSwag.CodeGeneration\SwaggerGenerators\SwaggerGenerator.cs:line 156
   at NSwag.CodeGeneration.SwaggerGenerators.SwaggerGenerator.GenerateAndAppendSchemaFromType(Type type, Boolean mayBeNull, IEnumerable`1 parentAttributes) in C:\projects\nswag\src\NSwag.CodeGeneration\SwaggerGenerators\SwaggerGenerator.cs:line 204
   at NSwag.CodeGeneration.SwaggerGenerators.SwaggerGenerator.CreateBodyParameter(String name, ParameterInfo parameter) in C:\projects\nswag\src\NSwag.CodeGeneration\SwaggerGenerators\SwaggerGenerator.cs:line 133
   at CallSite.Target(Closure , CallSite , OperationParameterProcessor , Object , ParameterInfo , SwaggerOperation , SwaggerGenerator )
   at CallSite.Target(Closure , CallSite , OperationParameterProcessor , Object , ParameterInfo , SwaggerOperation , SwaggerGenerator )
   at NSwag.CodeGeneration.SwaggerGenerators.WebApi.Processors.OperationParameterProcessor.Process(OperationProcessorContext context) in C:\projects\nswag\src\NSwag.CodeGeneration\SwaggerGenerators\WebApi\Processors\OperationParameterProcessor.cs:line 72
   at NSwag.CodeGeneration.SwaggerGenerators.WebApi.WebApiToSwaggerGenerator.RunOperationProcessors(SwaggerDocument document, MethodInfo methodInfo, SwaggerOperationDescription operationDescription, List`1 allOperations, SwaggerGenerator swaggerGenerator) in C:\projects\nswag\src\NSwag.CodeGeneration\SwaggerGenerators\WebApi\WebApiToSwaggerGenerator.cs:line 182
   at NSwag.CodeGeneration.SwaggerGenerators.WebApi.WebApiToSwaggerGenerator.AddOperationDescriptionsToDocument(SwaggerDocument document, List`1 operations, SwaggerGenerator swaggerGenerator) in C:\projects\nswag\src\NSwag.CodeGeneration\SwaggerGenerators\WebApi\WebApiToSwaggerGenerator.cs:line 162
   at NSwag.CodeGeneration.SwaggerGenerators.WebApi.WebApiToSwaggerGenerator.GenerateForController(SwaggerDocument document, Type controllerType, SwaggerGenerator swaggerGenerator) in C:\projects\nswag\src\NSwag.CodeGeneration\SwaggerGenerators\WebApi\WebApiToSwaggerGenerator.cs:line 150
   at NSwag.CodeGeneration.SwaggerGenerators.WebApi.WebApiToSwaggerGenerator.GenerateForControllers(IEnumerable`1 controllerTypes) in C:\projects\nswag\src\NSwag.CodeGeneration\SwaggerGenerators\WebApi\WebApiToSwaggerGenerator.cs:line 88
   at NSwag.AspNetCore.SwaggerMiddleware.GenerateSwagger(HttpContext context)
```

**Reproduce**:
```
        public class Smth : IEnumerable<string>
        {
            IEnumerator IEnumerable.GetEnumerator()
            {
                return GetEnumerator();
            }

            public IEnumerator<string> GetEnumerator()
            {
                throw new NotImplementedException();
            }
        }
```

```
Smth request = new Smth();
var type = request.GetType();
// type.GenericTypeArguments.Length -> return 0
// type.GetElementType() -> return null
```

I can't tell for sure, but I imagine that the SwaggerGenerator reports this type to be an array, but GetElementType() return null.

**Comment by rsuter** [comment]
This should be treated as array of string?

**Comment by rsuter** [comment]
Is this issue solved for you?

**Comment by georgeonofrei** [comment]
I will test it.
The situation is a bit complicated as the class I am binding to inherits ienumerable but also defines some properties. It is like that because the endpoint supports dynamic parameters - some are fixed and the requestor can fill in some custom properties.
It's a good question whether it should be a collection or an object - maybe it would be useful to have some attributes to help NSwag with the generation.

**Comment by rsuter** [comment]
I think you need to implement a type mapper: https://github.com/NJsonSchema/NJsonSchema/wiki/Type-Mappers

Do you have an idea how to handle your scenario in a generic way?
