### ISSUE TITLE
Generating Swagger Specification of a service that returns/accepts XML instead of JSON generates exception.

### ISSUE THREAD

**Issue by dcjulian29** [NSwag/NSwag#484]
I just downloaded the latest version of NSwagStudio and ran it against the code... I am getting the exception... "The JSON property 'ItemOf' is defined multiple times on type 'System.Xml.XmlAttributeCollection'. 

The class that is generating this...
```
public class QuestionController : ApiController
{
    private IRepository<QuestionTemplate, int> _templateRepository;

    public QuestionController(IRepository<QuestionTemplate, int> templateRepository)
    {
        _templateRepository = templateRepository;
    }

    public QuestionController()
    {
    }

    [ValidAccessTokenRequired]
    public HttpResponseMessage Get(int id)
    {
        using (var repository = _templateRepository ?? new QuestionRepository())
        {
            var entity = repository.FindById(id);

            if (entity == null)
            {
                return new HttpResponseMessage(HttpStatusCode.NotFound);
            }

            return new HttpResponseMessage
            {
                Content = new StringContent(entity.Template.OuterXml, Encoding.UTF8, "application/xml")
            };
        }
    }

    [SuperUserRequired]
    public IHttpActionResult Post([FromBody]XmlDocument xmlDocument)
    {
        var entity = new QuestionTemplate(xmlDocument.OuterXml);

        using (var repository = _templateRepository ?? new QuestionRepository())
        {
            repository.Save(entity);
        }

        var location = Url.Link(
            "DefaultApi",
            new
            {
                id = entity.Id.ToString()
            });

        return Created(location, entity);
    }

    [SuperUserRequired]
    public IHttpActionResult Post(string xmlContent)
    {
        var xml = new XmlDocument();

        try
        {
            xml.LoadXml(xmlContent);
        }
        catch (Exception)
        {
            return BadRequest();
        }

        return Post(xml);
    }
}
```

**Comment by rsuter** [comment]
By default "xmlDocument" is null when the operation is called. When I use 

    config.Formatters.XmlFormatter.UseXmlSerializer = true;

Then the JSON serializer is disabled everywhere...
How can I specify that only the request of `IHttpActionResult Post([FromBody]XmlDocument xmlDocument)` must be read with the XML serializer?

**Comment by dcjulian29** [comment]
I do this in my `startup.cs`  so that the XML is tried first before the JSON...
```
            var xmlFormatter = config.Formatters
                .Where(f => f.SupportedMediaTypes.Any(m => m.MediaType == "application/xml"))
                .ToList().First();

            config.Formatters.Remove(xmlFormatter);
            config.Formatters.Insert(0, xmlFormatter);

            config.Formatters.XmlFormatter.UseXmlSerializer = true;
```
It was the only way to get the XML serializer to attempt it first before the JSON would try... I never found a way to do it per controller/action... I have another part of the web service that does use JSON and the model binding seems to pick the JSON in that payload.

**Comment by rsuter** [comment]
I've implemented xml params in the web api to swagger, cs and ts generators... I just wanted to write an integration test so that i can test the full pipeline..

**Comment by dcjulian29** [comment]
@rsuter FYI... I just tried the 769 build and it worked on the POST to the controller it was failing on before... but it fails on one of the other controllers that uses PUT instead of POST...

**Comment by dcjulian29** [comment]
@rsuter sorry... it is working on a different controller that does have a PUT so it is not that... This is the stack trace I get:
```
System.InvalidOperationException: The method 'Post' on path '/Allergy' is registered multiple times.

Server stack trace: 
   at NSwag.CodeGeneration.SwaggerGenerators.WebApi.WebApiToSwaggerGenerator.<AddOperationDescriptionsToDocumentAsync>d__12.MoveNext() in C:\projects\nswag\src\NSwag.CodeGeneration\SwaggerGenerators\WebApi\WebApiToSwaggerGenerator.cs:line 160
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.CodeGeneration.SwaggerGenerators.WebApi.WebApiToSwaggerGenerator.<GenerateForControllerAsync>d__11.MoveNext() in C:\projects\nswag\src\NSwag.CodeGeneration\SwaggerGenerators\WebApi\WebApiToSwaggerGenerator.cs:line 148
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.CodeGeneration.SwaggerGenerators.WebApi.WebApiToSwaggerGenerator.<GenerateForControllersAsync>d__9.MoveNext() in C:\projects\nswag\src\NSwag.CodeGeneration\SwaggerGenerators\WebApi\WebApiToSwaggerGenerator.cs:line 87
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.CodeGeneration.SwaggerGenerators.WebApi.WebApiAssemblyToSwaggerGenerator.WebApiAssemblyLoader.<GenerateForControllersAsync>d__1.MoveNext() in C:\projects\nswag\src\NSwag.AssemblyLoaderCore\SwaggerGenerators\WebApi\WebApiAssemblyToSwaggerGenerator.cs:line 102
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.CodeGeneration.SwaggerGenerators.WebApi.WebApiAssemblyToSwaggerGenerator.WebApiAssemblyLoader.GenerateForControllers(IEnumerable`1 controllerClassNames, String settingsData) in C:\projects\nswag\src\NSwag.AssemblyLoaderCore\SwaggerGenerators\WebApi\WebApiAssemblyToSwaggerGenerator.cs:line 91
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NSwag.CodeGeneration.SwaggerGenerators.WebApi.WebApiAssemblyToSwaggerGenerator.WebApiAssemblyLoader.GenerateForControllers(IEnumerable`1 controllerClassNames, String settingsData)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.CodeGeneration.SwaggerGenerators.WebApi.WebApiAssemblyToSwaggerGenerator.<GenerateForControllersAsync>d__2.MoveNext() in C:\projects\nswag\src\NSwag.AssemblyLoaderCore\SwaggerGenerators\WebApi\WebApiAssemblyToSwaggerGenerator.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.WebApiToSwaggerCommandBase.<<RunAsync>b__67_0>d.MoveNext() in C:\projects\nswag\src\NSwag.Commands\Commands\WebApiToSwaggerCommandBase.cs:line 176
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.WebApiToSwaggerCommandBase.<RunAsync>d__67.MoveNext() in C:\projects\nswag\src\NSwag.Commands\Commands\WebApiToSwaggerCommandBase.cs:line 159
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwagStudio.ViewModels.SwaggerGenerators.WebApiToSwaggerGeneratorViewModel.<<GenerateSwaggerAsync>b__27_1>d.MoveNext() in C:\projects\nswag\src\NSwagStudio\ViewModels\SwaggerGenerators\WebApiToSwaggerGeneratorViewModel.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwagStudio.ViewModels.SwaggerGenerators.WebApiToSwaggerGeneratorViewModel.<<GenerateSwaggerAsync>b__27_0>d.MoveNext() in C:\projects\nswag\src\NSwagStudio\ViewModels\SwaggerGenerators\WebApiToSwaggerGeneratorViewModel.cs:line 102
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MyToolkit.Mvvm.ViewModelBase.<>c__DisplayClass15_0`1.<<RunTaskAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MyToolkit.Mvvm.ViewModelBase.<RunTaskAsync>d__12`1.MoveNext()
```

**Comment by rsuter** [comment]
Is the DefaultUrlTemplate correct (the default is "api/{controller}/{id}"); you may use "api/{controller}/{action}/{id}"...

Otherwise you have two PUT action methods with the same route which is not allowed in Swagger... You can use [SwaggerIgnore] to ignore one action method... 

Or maybe this is a scenario which is not supported... Can you post a sample where this happens?

**Comment by dcjulian29** [comment]
I think you are right... The web service was originally setup to accept but `text/plain' and 'application/xml' using the same route. The Model Binding in MVC handles which method gets called. I'll add the SwaggerIgnore to the 'text/plain' methods. Thanks.

**Comment by dcjulian29** [comment]
Adding the `[SwaggerIgnore]` and then re-compiling the assembly doesn't make the error go away... I even tried to restart NSwagStudio...
