### ISSUE TITLE
System.InvalidOperationException: Sequence contains no elements in MultipleClientsFromPathSegmentsOperationNameGenerator when path has no elements

### ISSUE THREAD

**Issue by paulomorgado** [NSwag/NSwag#593]
For this Swagger definition:

```
{
  "paths": {
    "/{id}": {
      "get": {
        "responses": {
          "200": {
            "schema": { "$ref": "#/definitions/touchpoint" },
            "description": "Touch points list"
          },
          "404": { "description": "Touch point not found" }
        },
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "type": "string",
            "required": true
          }
        ],
        "x-auth-type": "Application & Application User",
        "x-throttling-tier": "Unlimited"
      },
      "put": {
        "responses": { "200": { "description": "Created or updated" } },
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "type": "string",
            "required": true
          },
          {
            "schema": { "$ref": "#/definitions/touchpoint" },
            "in": "body",
            "name": "touchpoint",
            "required": true
          }
        ],
        "x-auth-type": "Application & Application User",
        "x-throttling-tier": "Unlimited"
      }
    },
    "/*": {
      "post": {
        "responses": {
          "201": {
            "schema": { "$ref": "#/definitions/touchpoint" },
            "headers": { "Location": { "type": "string" } },
            "description": "Created"
          }
        },
        "parameters": [
          {
            "schema": { "$ref": "#/definitions/touchpoint" },
            "in": "body",
            "name": "touchpoint",
            "required": true
          }
        ],
        "x-auth-type": "Application & Application User",
        "x-throttling-tier": "Unlimited"
      },
      "get": {
        "responses": {
          "200": {
            "schema": {
              "type": "array",
              "items": { "$ref": "#/definitions/touchpoint" }
            },
            "description": "Touch points list"
          }
        },
        "parameters": [
          {
            "in": "query",
            "name": "type",
            "type": "string",
            "required": false
          }
        ],
        "x-auth-type": "Application & Application User",
        "x-throttling-tier": "Unlimited"
      }
    }
  },
  "schemes": [ "https", "http" ],
  "definitions": {
    "touchpoint": {
      "type": "object",
      "properties": {
        "Type": { "type": "string" },
        "Version": { "type": "string" },
        "Model": { "type": "string" },
        "Id": { "type": "string" }
      }
    }
  },
  "swagger": "2.0",
  "info": {
    "description": "Touch Point Management interface",
    "title": "Touch Point Management",
    "version": "1.0.0"
  }
}
```

I'm getting this error generating the client:

```
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at NSwag.CodeGeneration.OperationNameGenerators.MultipleClientsFromPathSegmentsOperationNameGenerator.GetOperationName(SwaggerDocument document, String path, SwaggerOperationMethod httpMethod, SwaggerOperation operation)
   at NSwag.CodeGeneration.ClientGeneratorBase`3.<>c__DisplayClass12_1.<GetOperations>b__2(<>f__AnonymousType0`3 tuple)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NSwag.CodeGeneration.ClientGeneratorBase`3.GetOperations(SwaggerDocument document)
   at NSwag.CodeGeneration.ClientGeneratorBase`3.GenerateFile(SwaggerDocument document, ClientGeneratorOutputType type)
   at NSwag.CodeGeneration.CSharp.SwaggerToCSharpClientGenerator.GenerateFile()
   at Microsoft.VisualStudio.TextTemplating14D6AA0DFDFE7695460927542EC03E29927A9CBB6405D591ED813AACD385AAF3299FE2112D9C621AA83287D3BA8D034559F996A6B5D23B57635ED2D7F8440861.GeneratedTextTransformation.TransformText()	VisionBox.TransactionManager.Services.Clients	C:\Projects\PRODUCTS\TransactionManager\src\VisionBox.Services.Clients\TouchPoint\TouchPointManagement.tt	1	
```

Looks like the problem is the `GetOperationName` method:

```
public string GetOperationName(SwaggerDocument document, string path, SwaggerOperationMethod httpMethod, SwaggerOperation operation)
{
    var pathSegments = path.Split('/').Where(p => !p.Contains("{")).Reverse().ToArray();
    return pathSegments.First();
}
```

Changing to this works fine:

```
public string GetOperationName(SwaggerDocument document, string path, SwaggerOperationMethod httpMethod, SwaggerOperation operation)
{
    return path.Split('/').Where(p => !p.Contains("{")).Reverse().FirstOrDefault() ?? string.Empty;
}
```

I would also change `GetClientName` to:

```
public string GetClientName(SwaggerDocument document, string path, SwaggerOperationMethod httpMethod, SwaggerOperation operation)
{
    return path.Split('/').Where(p => !p.Contains("{")).Reverse().Skip(1).FirstOrDefault() ?? string.Empty;
}
```

If you're already paying the LINQ tax, there's no need to pay the array allocation tax.

**Comment by rsuter** [comment]
Don't you have other problems when you just return an empty string?

**Comment by paulomorgado** [comment]
Well, I get a bunch of methods with the same name, but, for now, I'm using string replacement to solve it.

A MultipleClientsFromPathSegmentsOperationNameGenerator that uses the method will solve them.

But it doesn't crash I can see where it went wrong.

**Comment by rsuter** [comment]
Is this commit fine for you? Please try the change with the latest CI artifacts

**Comment by paulomorgado** [comment]
It no longer throws.

But while the `/{id}` path generates `IndexAsync` method names and `string.Format("{0}/{1}", BaseUrl, "{id}")` URLs, the `/` path generates `Async` method names and `string.Format("{0}/{1}", BaseUrl, "")`.

Was that what you're expecting?

**Comment by rsuter** [comment]
I think in this scenario you shouldn't use this operation name generator. Generally it is only working when you have paths in the form "api/controller/action"
