### ISSUE TITLE
Error:The given path's format is not supported.

### ISSUE THREAD

**Issue by robertatsage** [NSwag/NSwag#602]
I get an error: The given path's format is not supported when I open a swagger definition:

[Elements.zip](https://github.com/NSwag/NSwag/files/782883/Elements.zip)

Stack:

System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at NSwag.Commands.NSwagDocument.ConvertToAbsolutePath(String pathToConvert) in C:\projects\nswag\src\NSwag.AssemblyLoaderCore\NSwagDocument.cs:line 51
   at NSwag.Commands.NSwagDocumentBase.ConvertToAbsolutePaths() in C:\projects\nswag\src\NSwag.Commands\NSwagDocumentBase.cs:line 214
   at NSwag.Commands.NSwagDocumentBase.<>c__DisplayClass26_0`1.<<LoadAsync>b__0>d.MoveNext() in C:\projects\nswag\src\NSwag.Commands\NSwagDocumentBase.cs:line 159
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwagStudio.ViewModels.MainWindowModel.<>c__DisplayClass32_0.<<OpenDocumentAsync>b__0>d.MoveNext() in C:\projects\nswag\src\NSwagStudio\ViewModels\MainWindowModel.cs:line 141
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MyToolkit.Mvvm.ViewModelBase.<>c__DisplayClass14_0.<<RunTaskAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MyToolkit.Mvvm.ViewModelBase.<RunTaskAsync>d__12`1.MoveNext()

**Comment by rsuter** [comment]
Somehow the path is wrong... Are the paths correct?

**Comment by robertatsage** [comment]
The url in the document used a local file, this used to work in te previous version.
 
"url": "file:\\\\C:\\sandbox\\sic\\api\\cloud-elements\\Formulas.json"

I have cleared the url and it worked fine.

**Comment by rsuter** [comment]
Ah I changed that so that paths are supported. Just use 

    "url": "C:\sandbox\sic\api\cloud-elements\Formulas.json"

without "file://"

**Comment by robertatsage** [comment]
Thanks!!
