### ISSUE TITLE
After commit 'e645dfc0' I'm unable to load swagger service from url.

### ISSUE THREAD

**Issue by DerekChasse** [NSwag/NSwag#71]

**Comment by DerekChasse** [comment]
Actually adding description this time.

Receiving the following when invoking SwaggerService.FromUrl:

```
{
  "Message": "An error has occurred.",
  "ExceptionMessage": "Could not load type 'System.Net.WebClient' from assembly 'NSwag.Core, Version=2.10.5958.26958, Culture=neutral, PublicKeyToken=c2d88086e098d109'.",
  "ExceptionType": "System.TypeLoadException",
  "StackTrace": "   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
at System.Type.GetType(String typeName, Boolean throwOnError)
at NSwag.SwaggerService.FromUrl(String url)  

..SNIPPED.."
}
```

Any guidance would be greatly appreciated.  This is in a WebAPI application, but is parsing Swagger contracts, not producing them.

**Comment by rsuter** [comment]
On what platform are you calling the method? It is only supported on the full .NET 4.5+...

**Comment by DerekChasse** [comment]
Target framework is 4.5.2 and this is not a portable assembly.

I will work on a sample application for you.

**Comment by DerekChasse** [comment]
Reproducible here:

[SwaggerRepro.zip](https://github.com/NSwag/NSwag/files/236940/SwaggerRepro.zip)

**Comment by rsuter** [comment]
ok fixed in v2.11

**Comment by DerekChasse** [comment]
Thanks so much for the quick turnaround.  Thanks for the project as well.

**Comment by rsuter** [comment]
Thanks for using NSwag
