### ISSUE TITLE
Command line returning  "Value cannot be null. Parameter name: assemblyDirectory" ?

### ISSUE THREAD

**Issue by CastleSoft** [NSwag/NSwag#73]
Create a new Project -> WebApplication -> WEBAPI and compile to produce WebApplication1.dll

NSwagStudio generates everything ok, when I try via the command line with the following:

nswag webapi2swagger /assembly:WebApplication1.dll /controller:WebApplication1.Controllers.ValuesController /output:MyWebService.json

The error returned is: (Am I missing a parameter ? setting ?)
===============================================================================

NSwag command line: v2.11.5960.28622
Visit http://NSwag.org for more information.
Execute the 'help' command to show a list of all the available commands.
System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: assemblyDirectory
   at NSwag.CodeGeneration.Infrastructure.AppDomainIsolation`1..ctor(String assemblyDirectory) in C:\projects\nswag\src\NSwag.CodeGeneration\Infrastructure\AppDomainIsolation.cs:line 19
   at NSwag.CodeGeneration.SwaggerGenerators.WebApi.WebApiAssemblyToSwaggerGenerator.GenerateForControllers(IEnumerable`1 controllerClassNames) in C:\projects\nswag\src\NSwag.CodeGeneration\SwaggerGenerators\WebApi\WebApiAssemblyToSwaggerGenerator.cs:line 62
   at NSwag.Commands.WebApiToSwaggerCommand.<RunAsync>d__32.MoveNext() in C:\projects\nswag\src\NSwag\Commands\WebApiToSwaggerCommand.cs:line 97

**Comment by rsuter** [comment]
Should be fixed soon

**Comment by rsuter** [comment]
Commit: https://github.com/NSwag/NSwag/commit/16dea6b33495e4778904b49fc5f99d2440be4e89
Fix in NConsole: https://github.com/NConsole/NConsole/commit/61c5da9ca7c422be66624fa486c25fabb63b5341

**Comment by rsuter** [comment]
Ok, try again with v2.12

**Comment by rsuter** [comment]
Release: https://github.com/NSwag/NSwag/releases/tag/NSwag-Build-427
