### ISSUE TITLE
nswag.exe cmd --help handling

### ISSUE THREAD

**Issue by balazserdos** [NSwag/NSwag#758]
Would be nice if NSwag CLI handled --help. I think this is the first that is invoked using a CLI. 

C:\Users\MyUser>nswag --help

```
NSwag command line tool for .NET 4.6+, toolchain v10.6.6324.28497 (NJsonSchema v8.33.6323.36213) (x64)
Visit http://NSwag.org for more information.
NSwag bin directory: D:\Utilities\NSwag
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: The command '--help' could not be found.
   at NConsole.CommandLineProcessor.<ProcessSingleAsync>d__12.MoveNext() in C:\projects\nconsole\src\NConsole\CommandLineProcessor.cs:line 147
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NConsole.CommandLineProcessor.<ProcessAsync>d__11.MoveNext() in C:\projects\nconsole\src\NConsole\CommandLineProcessor.cs:line 107
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 59
---> (Inner Exception #0) System.InvalidOperationException: The command '--help' could not be found.
   at NConsole.CommandLineProcessor.<ProcessSingleAsync>d__12.MoveNext() in C:\projects\nconsole\src\NConsole\CommandLineProcessor.cs:line 147
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NConsole.CommandLineProcessor.<ProcessAsync>d__11.MoveNext() in C:\projects\nconsole\src\NConsole\CommandLineProcessor.cs:line 107<---
```

**Comment by snmed** [comment]
Hi @balazserdos 
If you omit --, nswag shows you a comprehensive help overview. Or if you call nswag without a parameter, it prints:
```
NSwag command line tool for .NET 4.6+, toolchain v9.12.6305.13035 (NJsonSchema v8.30.6304.31883) (x64)
Visit http://NSwag.org for more information.
NSwag bin directory: C:\Program Files (x86)\Rico Suter\NSwagStudio
Execute the 'help' command to show a list of all the available commands.

Command
```
Hope that helps, cheers

**Comment by balazserdos** [comment]
thank you :)
