### ISSUE TITLE
Object Reference Exception being thrown after getting latest packages

### ISSUE THREAD

**Issue by cwoolum** [NSwag/NSwag#80]
I just updated to the newest Nuget Packages and I'm getting the following error. The exception seems to be thrown when the SwaggerToCSharpTypeResolver calls its base Resolve method. For some reason schema is null even though it is not in the method calling it.

```
Error		Running transformation: System.NullReferenceException: Object reference not set to an instance of an object.
   at NJsonSchema.CodeGeneration.TypeScript.TypeScriptTypeResolver.Resolve(JsonSchema4 schema, Boolean isNullable, String typeNameHint) in C:\projects\njsonschema\src\NJsonSchema.CodeGeneration\TypeScript\TypeScriptTypeResolver.cs:line 45
   at NJsonSchema.CodeGeneration.TypeScript.TypeScriptTypeResolver.Resolve(JsonSchema4 schema, Boolean isNullable, String typeNameHint) in C:\projects\njsonschema\src\NJsonSchema.CodeGeneration\TypeScript\TypeScriptTypeResolver.cs:line 85
   at NSwag.CodeGeneration.CodeGenerators.TypeScript.SwaggerToTypeScriptClientGenerator.GetType(JsonSchema4 schema, String typeNameHint) in C:\projects\nswag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\SwaggerToTypeScriptClientGenerator.cs:line 115
   at NSwag.CodeGeneration.CodeGenerators.TypeScript.SwaggerToTypeScriptClientGenerator.GetResultType(SwaggerOperation operation) in C:\projects\nswag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\SwaggerToTypeScriptClientGenerator.cs:line 102
   at NSwag.CodeGeneration.CodeGenerators.ClientGeneratorBase.<>c__DisplayClass10_1`1.<GetOperations>b__2(<>f__AnonymousType0`3 tuple) in C:\projects\nswag\src\NSwag.CodeGeneration\CodeGenerators\ClientGeneratorBase.cs:line 87
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NSwag.CodeGeneration.CodeGenerators.ClientGeneratorBase.GetOperations[TGenerator](SwaggerService service, TypeResolverBase`1 resolver) in C:\projects\nswag\src\NSwag.CodeGeneration\CodeGenerators\ClientGeneratorBase.cs:line 72
   at NSwag.CodeGeneration.CodeGenerators.ClientGeneratorBase.GenerateFile[TGenerator](SwaggerService service, TypeResolverBase`1 resolver) in C:\projects\nswag\src\NSwag.CodeGeneration\CodeGenerators\ClientGeneratorBase.cs:line 50
   at NSwag.CodeGeneration.CodeGenerators.TypeScript.SwaggerToTypeScriptClientGenerator.GenerateFile() in C:\projects\nswag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\SwaggerToTypeScriptClientGenerator.cs:line 53
	
```

Here is the relevant swagger definition

```
{
  "swagger": "2.0",
  "info": {
    "version": "v1",
    "title": "Test API"
  },
  "host": "localhost:7818",
  "schemes": [
    "http"
  ],
  "paths": {
    "/api/Account/ChangePassword": {
      "post": {
        "tags": [
          "Account"
        ],
        "operationId": "Account_ChangePassword",
        "consumes": [
          "application/json",
          "text/json",
          "application/xml",
          "text/xml",
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "application/json",
          "text/json",
          "application/xml",
          "text/xml"
        ],
        "parameters": [
          {
            "name": "model",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ChangePasswordBindingModel"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Object"
            }
          }
        },
        "deprecated": false
      }
    }
}
}
```

**Comment by cwoolum** [comment]
![image](https://cloud.githubusercontent.com/assets/942415/14955748/f1845e76-1030-11e6-8946-25fae1450947.png)

**Comment by rsuter** [comment]
Can you post the full Swagger spec (i.e. the missing definitions)

**Comment by cwoolum** [comment]
I dug in a bit more and this looks like an issue with my schema generation. 

```
"schema": {
              "$ref": "#/definitions/Object"
            }
``` 
should actually not be there. That definition was not getting rendered so I think that is what was breaking the generation. .

**Comment by rsuter** [comment]
So, you think the reference could not be resolved?

**Comment by cwoolum** [comment]
Yeah, from what I can tell. It might be helpful to have an exception
message explaining that the definition of the type could not be found but
I'm not sure if this would be a common problem.

**Comment by rsuter** [comment]
I already got the following error msg: 

![image](https://cloud.githubusercontent.com/assets/2603405/14965164/16c3ed98-10ac-11e6-942c-5eb187f9788f.png)

Strange that you see a different message...
