### ISSUE TITLE
C# T4 template is not working.

### ISSUE THREAD

**Issue by prakash-patel** [NSwag/NSwag#87]
NuGet Packages i am using

```c#
    <package id="Antlr" version="3.5.0.2" targetFramework="net45" />
  <package id="Antlr4.StringTemplate" version="4.0.6.9004" targetFramework="net45" />
  <package id="Newtonsoft.Json" version="8.0.3" targetFramework="net45" />
  <package id="NJsonSchema" version="2.14.5967.31319" targetFramework="net45" />
  <package id="NJsonSchema.CodeGeneration" version="2.14.5967.31320" targetFramework="net45" />
  <package id="NSwag.CodeGeneration" version="2.16.5968.25805" targetFramework="net45" />
  <package id="NSwag.Core" version="2.16.5968.25804" targetFramework="net45" />
```

my .tt file
```c#
<#@ template debug="false" hostspecific="true" language="C#" #>

<#@ assembly name="System.Core" #>
<#@ assembly name="System.Runtime" #>
<#@ assembly name="$(SolutionDir)NSwag.CodeGeneration\NJsonSchema.CodeGeneration.dll" #>
<#@ assembly name="$(SolutionDir)NSwag.CodeGeneration\NSwag.CodeGeneration.dll" #>
<#@ assembly name="$(SolutionDir)NSwag.CodeGeneration\NSwag.Core.dll" #>

<#@ import namespace="NSwag" #>

<#@ import namespace="System.IO" #>
<#@ import namespace="Microsoft.CSharp" #>
<#@ import namespace="NSwag.CodeGeneration.CodeGenerators.CSharp" #>

<#@ output extension=".cs" #>
<#
	// CONFIGURATION
	var url = @"http://localhost:5524/swagger/docs/v2";
	// -------------

	var service = SwaggerService.FromUrl(url);

    var provider = new CSharpCodeProvider();
    var settings = new SwaggerToCSharpClientGeneratorSettings
    {
        ClassName = provider.CreateEscapedIdentifier(Path.GetFileNameWithoutExtension(Host.TemplateFile)),
    };
    settings.CSharpGeneratorSettings.Namespace = Host.ResolveParameterValue("directiveId", "namespaceDirectiveProcessor", "namespaceHint");
    var clientGenerator = new SwaggerToCSharpClientGenerator(service, settings);
    var code = clientGenerator.GenerateFile();

#>
<#= code #>
```

I am getting error when i try to geneate code.
```c#
Severity	Code	Description	Project	File	Line	Suppression State
Error		Running transformation: System.NullReferenceException: Object reference not set to an instance of an object.
   at NSwag.CodeGeneration.CodeGenerators.CSharp.SwaggerToCSharpTypeResolver.Resolve(JsonSchema4 schema, Boolean isNullable, String typeNameHint)
   at NJsonSchema.CodeGeneration.CSharp.CSharpTypeResolver.Resolve(JsonSchema4 schema, Boolean isNullable, String typeNameHint)
   at NSwag.CodeGeneration.CodeGenerators.CSharp.SwaggerToCSharpTypeResolver.Resolve(JsonSchema4 schema, Boolean isNullable, String typeNameHint)
   at NJsonSchema.CodeGeneration.CSharp.CSharpTypeResolver.Resolve(JsonSchema4 schema, Boolean isNullable, String typeNameHint)
   at NSwag.CodeGeneration.CodeGenerators.CSharp.SwaggerToCSharpTypeResolver.Resolve(JsonSchema4 schema, Boolean isNullable, String typeNameHint)
   at NJsonSchema.CodeGeneration.CSharp.CSharpGenerator.<GenerateType>b__12_0(JsonProperty property)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NJsonSchema.CodeGeneration.CSharp.CSharpGenerator.GenerateType(String fallbackTypeName)
   at NJsonSchema.CodeGeneration.TypeResolverBase`1.GenerateTypes()
   at NSwag.CodeGeneration.CodeGenerators.CSharp.SwaggerToCSharpClientGenerator.RenderFile(String clientCode)
   at NSwag.CodeGeneration.CodeGenerators.ClientGeneratorBase.GenerateFile[TGenerator](SwaggerService service, TypeResolverBase`1 resolver)
   at NSwag.CodeGeneration.CodeGenerators.CSharp.SwaggerToCSharpClientGenerator.GenerateFile()
   at Microsoft.VisualStudio.TextTemplatingAF163D4E5337BBCE7854DFDD8672CF389E34872FDF0E8E107A0C6A2A37B69F114CB7ADBAC7EA32D7CABDE806D623F00B30BCF1B0237D9E9A054EA9994174D531.GeneratedTextTransformation.TransformText()	

```

Please let me know if i am doing anything wrong here?

**Comment by rsuter** [comment]
Can you post the swagger spec?

**Comment by prakash-patel** [comment]
I used below old packages for `NSwag.CodeGeneration` and it's works fine.
```c#
  <package id="Antlr" version="3.4.1.9004" targetFramework="net45" />
  <package id="Antlr4.StringTemplate" version="4.0.6.9004" targetFramework="net45" />
  <package id="Newtonsoft.Json" version="8.0.3" targetFramework="net45" />
  <package id="NJsonSchema" version="2.0.5928.2914" targetFramework="net45" />
  <package id="NJsonSchema.CodeGeneration" version="2.0.5928.2915" targetFramework="net45" />
  <package id="NSwag.CodeGeneration" version="2.2.5928.27983" targetFramework="net45" />
  <package id="NSwag.Core" version="2.2.5928.27982" targetFramework="net45" />
```

**Comment by prakash-patel** [comment]
```json
{swagger: "2.0",
info: {
version: "v2",
title: "News"
},
host: "www.goodinfo.com",
basePath: "/news",
schemes: [
"https"
],
paths: {}
}
```
My application running under `www.goodinfo.com/News`. Look like NSwag doesn't include BasePath (/News) when it's generate client code. Or do i need to include in SwaggerConfig.cs?

**Comment by rsuter** [comment]
Can you try again with v2.17, the Swagger spec works for me in NSwagStudio...

**Comment by prakash-patel** [comment]
I try it and it's working fine with ```v2.18```

**Comment by rsuter** [comment]
Ok, thx for reporting... and thanks for using NSwag.
